### ISSUE TITLE
Interested in helping (0Arc from reddit)

### ISSUE THREAD

**Issue by ghost** [deeredman1991/Twitch-Plays-Bot#2]
Hey just  wanted to let you know i'm interested in helping,
If you can give me a todo list would be nice :+1:

**Comment by twitchplayskh** [comment]
well the bot needs a lot of work till we can start in a todo list lot of bugs and we need to make adding a new emu not so hard and work as well

**Comment by deeredman1991** [comment]
Welcome aboard...you are now a collaborator. :) I am no longer actively developing the bot, but I may be able to throw in a few lines of code every now and then. If you have any questions let me know. :)

As far as a todo list is concerned; that is up to you and twitchplayshk. :)

If I still had time to develop the bot; I _personally_ would re-write the bot so that the user makes a config file with a list of commands and what button the commands press on the keyboard(or mouse) and for how long. This way it makes it highly configurable no matter what game is being played.

A few things that I was doing before I had to quit;

*Replacing PyWin32 with a library that would work with ALL emulators and games including PC games(this would also require mouse support, perhaps consider the ahk library for python, but it's your call)

*twitchplayskh wants it to be able to emulate a controller.

*Making sure the program could pause ANY process the program wants to pause so that it can work with all games and programs (this may possibly involve replacing psutil) half the time it works, half the time it doesn't, and often it requires special patchy code to get certain programs to work and/or pause and unpause. (an example of patchy code is how the program works when pausing and unpausing the ps2 emulator)

*Hooking the emulator or program so that the bot could send input to it directly without it having to be the active window thereby freeing up the keyboard and mouse for other tasks such as moderating chat twitchplayskh has also expressed an interest in running multiple bots/streams on one PC...this would definitely help with that.

*Dolphin Support

*Twitchplayskh REALLY wants a G.U.I. lol (I would recommend Kivy, if you decide to take up this gauntlet, it's really easy to use and completely cross platform.)
